# Generated by Django 4.2.2 on 2023-07-07 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='name_h',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='password',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='phone',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
