# Generated by Django 4.2.2 on 2023-07-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_hospitals_name_h_remove_hospitals_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='site',
        ),
        migrations.RemoveField(
            model_name='hospitalservice',
            name='date_time',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='laditude',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='longitude',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='ip_t',
            field=models.CharField(choices=[('GO', 'Goverment'), ('PR', 'Private')], default='GO', max_length=2),
        ),
        migrations.DeleteModel(
            name='HospitalType',
        ),
    ]
