# Generated by Django 4.2.2 on 2023-07-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_transportscompany_pharmacies_mechanical_hospitals_and_more'),
        ('hospital', '0003_remove_hospitals_rating_remove_hospitals_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalservice',
            name='ip_h',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.hospitals'),
        ),
        migrations.DeleteModel(
            name='Hospitals',
        ),
    ]
