# Generated by Django 4.2.2 on 2023-07-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_hospitalservice_ip_h_delete_hospitals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competence',
        ),
    ]
