# Generated by Django 4.2 on 2023-05-01 14:52

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('ip_competence', models.IntegerField(primary_key=True, serialize=False)),
                ('competence', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ip_c', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254, verbose_name=builtins.max)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('ip_h', models.IntegerField(primary_key=True, serialize=False)),
                ('name_h', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('rating', models.IntegerField()),
                ('comments', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('site', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('ip_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.competence')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalType',
            fields=[
                ('ip_type', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=50, null=True)),
                ('ip_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.customer')),
                ('ip_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitals')),
            ],
        ),
        migrations.AddField(
            model_name='hospitals',
            name='ip_t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitaltype'),
        ),
    ]
