# Generated by Django 4.2 on 2023-05-09 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_hospitalservice_ip_c_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalservice',
            name='date_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
