# Generated by Django 4.2 on 2023-05-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospitalservice_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
