# Generated by Django 4.2 on 2023-05-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_hospitals_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalservice',
            name='review',
        ),
    ]
