# Generated by Django 4.2 on 2023-05-01 14:52

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ip_c', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254, verbose_name=builtins.max)),
            ],
        ),
        migrations.CreateModel(
            name='TransportsCompany',
            fields=[
                ('ip_tc', models.IntegerField(primary_key=True, serialize=False)),
                ('name_tc', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField()),
                ('site', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('comments', models.TextField(max_length=2500)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('ip_type', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('ip_t', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('phone', models.BigIntegerField()),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('ip_tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transportscompany')),
                ('ip_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transporttype')),
            ],
        ),
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=2500)),
                ('ip_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.customer')),
                ('ip_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.trips')),
            ],
        ),
    ]
