# Generated by Django 4.2 on 2023-05-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportservice',
            name='ip_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
