# Generated by Django 4.2 on 2023-05-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_transportservice_ip_c_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportservice',
            name='review',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='phone',
        ),
        migrations.AlterField(
            model_name='transportscompany',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='transportscompany',
            name='picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
