# Generated by Django 4.2 on 2023-05-01 14:52

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ip_c', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254, verbose_name=builtins.max)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('ip_m', models.IntegerField(primary_key=True, serialize=False)),
                ('medicine', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacies',
            fields=[
                ('ip_ph', models.IntegerField(primary_key=True, serialize=False)),
                ('name_ph', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('holiday', models.DateTimeField(choices=[('FR', 'Friday'), ('SU', 'Sunday'), ('MA', 'Manday'), ('TU', 'Tuseday'), ('WE', 'Wednesday'), ('TH', 'Thersday')], default='MA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacieServies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(choices=[('FR', 'Friday'), ('SU', 'Sunday'), ('MA', 'Manday'), ('TU', 'Tuseday'), ('WE', 'Wednesday'), ('TH', 'Thersday')], default='MA', max_length=2)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(max_length=5000)),
                ('ip_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.customer')),
                ('ip_ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacies')),
            ],
        ),
        migrations.CreateModel(
            name='PharmaciesContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.BooleanField()),
                ('ip_ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacies')),
                ('ip_pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine')),
            ],
        ),
    ]
