# Generated by Django 4.2 on 2023-05-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_pharmacieservies_ip_c_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacieservies',
            name='date_time',
            field=models.DateTimeField(choices=[('Friday', 'FR'), ('Sunday', 'SU'), ('Manday', 'MA'), ('Tuseday', 'TU'), ('Wednesday', 'WE'), ('Thersday', 'TH')], default='MA', max_length=10),
        ),
    ]
