# Generated by Django 4.2 on 2023-05-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_pharmacieservies_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacieservies',
            name='date_time',
            field=models.DateTimeField(choices=[('Friday', 'FRIDAY'), ('Sunday', 'SUNDAY'), ('Manday', 'MANDAY'), ('Tuseday', 'TUSEDAY'), ('Wednesday', 'WEDNESDAY'), ('Thersday', 'THERSDAY')], default='MANDAY', max_length=10),
        ),
    ]
