# Generated by Django 4.2 on 2023-05-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_pharmacieservies_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacies',
            name='holiday',
            field=models.DateTimeField(choices=[('Friday', 'FRIDAY'), ('Sunday', 'SUNDAY'), ('Manday', 'MANDAY'), ('Tuseday', 'TUSEDAY'), ('Wednesday', 'WEDNESDAY'), ('Thersday', 'THERSDAY')], max_length=10),
        ),
    ]
