# Generated by Django 4.2 on 2023-05-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_alter_pharmacies_holiday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacies',
            name='holiday',
            field=models.DateTimeField(choices=[('FR', 'Friday'), ('SU', 'Su'), ('MA', 'Manday'), ('TU', 'Tuseday'), ('WE', 'Wednesday'), ('TH', 'Thersday')], default='FR', max_length=2),
        ),
    ]
