# Generated by Django 4.2 on 2023-05-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_alter_pharmacies_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacies',
            name='holiday',
            field=models.CharField(choices=[('FR', 'Friday'), ('SU', 'Sunday'), ('MA', 'Manday'), ('TU', 'Tuseday'), ('WE', 'Wednesday'), ('TH', 'Thersday')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='pharmacieservies',
            name='date_time',
            field=models.CharField(choices=[('FR', 'Friday'), ('SU', 'Sunday'), ('MA', 'Manday'), ('TU', 'Tuseday'), ('WE', 'Wednesday'), ('TH', 'Thersday')], default='FR', max_length=2),
        ),
    ]
