# Generated by Django 4.2 on 2023-05-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_pharmacies_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacies',
            name='comments',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='site',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='work',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
