# Generated by Django 4.2 on 2023-05-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_alter_pharmacies_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacies',
            old_name='work',
            new_name='night_shift',
        ),
        migrations.RemoveField(
            model_name='pharmacies',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='pharmacieservies',
            name='review',
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='rate',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
