# Generated by Django 4.2 on 2023-05-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_rename_work_pharmacies_night_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacies',
            name='picture',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
