# Generated by Django 4.2 on 2023-05-01 14:52

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ip_c', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254, verbose_name=builtins.max)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanical',
            fields=[
                ('ip_m', models.IntegerField(primary_key=True, serialize=False)),
                ('name_m', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('work_time', models.DateTimeField()),
                ('holiday', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('comments', models.CharField(max_length=2500)),
                ('site', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVechale',
            fields=[
                ('ip_type', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('ip_type', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('rating', models.IntegerField(null=10)),
                ('review', models.CharField(max_length=2500)),
                ('ip_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanical.customer')),
                ('ip_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanical.mechanical')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanical.mechanical')),
                ('ip_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanical.typevechale')),
            ],
        ),
        migrations.AddField(
            model_name='mechanical',
            name='ip_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanical.typework'),
        ),
    ]
