# Generated by Django 4.2 on 2023-05-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0004_alter_mechanical_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanical',
            name='work_time',
        ),
        migrations.RemoveField(
            model_name='mechanicservice',
            name='review',
        ),
    ]
