# Generated by Django 4.2.2 on 2023-06-23 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('ip_m', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('medicine', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name_ph', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('duration', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('holiday', models.CharField(choices=[('FR', 'Friday'), ('SU', 'Sunday'), ('MA', 'Manday'), ('TU', 'Tuseday'), ('WE', 'Wednesday'), ('TH', 'Thersday')], default='FR', max_length=2)),
                ('night_shift', models.DateField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='static\\PublicServes\\images')),
                ('site', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_review', to='pharmacy.pharmacies')),
            ],
        ),
        migrations.CreateModel(
            name='PharmaciesServies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(choices=[('FR', 'Friday'), ('SU', 'Sunday'), ('MA', 'Manday'), ('TU', 'Tuseday'), ('WE', 'Wednesday'), ('TH', 'Thersday')], default='FR', max_length=2)),
                ('rating', models.CharField(max_length=1)),
                ('ip_ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacies', to='pharmacy.pharmacies')),
            ],
        ),
        migrations.CreateModel(
            name='PharmaciesContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.CharField(max_length=150)),
                ('ip_ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacies')),
                ('ip_pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicines')),
            ],
        ),
    ]
