# Generated by Django 4.2.2 on 2023-07-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_pharmacies_name_ph_remove_pharmacies_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacies',
            name='site',
        ),
        migrations.RemoveField(
            model_name='pharmaciesservies',
            name='date_time',
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='laditude',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='longitude',
            field=models.BigIntegerField(default=0),
        ),
    ]
