# Generated by Django 4.2.2 on 2023-07-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_remove_pharmacies_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacies',
            name='night_shift',
            field=models.BooleanField(default=False),
        ),
    ]
