# Generated by Django 4.2.2 on 2023-07-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_transportscompany_pharmacies_mechanical_hospitals_and_more'),
        ('pharmacy', '0004_alter_pharmacies_night_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaciescontents',
            name='ip_ph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.pharmacies'),
        ),
        migrations.AlterField(
            model_name='pharmaciesservies',
            name='ip_ph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacies', to='myprofile.pharmacies'),
        ),
        migrations.AlterField(
            model_name='pharmacyreview',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_review', to='myprofile.pharmacies'),
        ),
        migrations.DeleteModel(
            name='Pharmacies',
        ),
    ]
