# Generated by Django 4.2.2 on 2023-07-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_pharmaciescontents_ip_ph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='ip_m',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
