# Generated by Django 4.2 on 2023-05-01 14:52

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ip_c', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254, verbose_name=builtins.max)),
            ],
        ),
        migrations.CreateModel(
            name='Specializaion',
            fields=[
                ('ip_s', models.IntegerField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('ip_d', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('comments', models.CharField(max_length=2500, null=True)),
                ('work_time', models.DateTimeField()),
                ('rating', models.IntegerField()),
                ('holiday', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=70)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('password', models.CharField(max_length=50)),
                ('ip_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.specializaion')),
            ],
        ),
        migrations.CreateModel(
            name='DoctarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=50)),
                ('ip_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.customer')),
                ('ip_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctors')),
            ],
        ),
    ]
