# Generated by Django 4.2 on 2023-05-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctarservice_ip_c_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='m_name',
        ),
        migrations.AddField(
            model_name='doctors',
            name='fullname',
            field=models.TextField(default='dani barchene', max_length=55),
            preserve_default=False,
        ),
    ]
