# Generated by Django 4.2 on 2023-05-09 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctors_f_name_remove_doctors_l_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctarservice',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
