# Generated by Django 4.2 on 2023-05-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctors_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctarservice',
            name='review',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='work_time',
        ),
    ]
