# Generated by Django 4.2.2 on 2023-07-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='user_type',
            field=models.CharField(choices=[('US', 'User'), ('PH', 'Pharmacy'), ('ME', 'Mechanical'), ('TR', 'Transport'), ('DR', 'Doctor'), ('HO', 'Hospital')], default='US', max_length=2),
        ),
    ]
