# Generated by Django 4.2.2 on 2023-07-08 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_myprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportsCompany',
            fields=[
                ('ip_tc', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('longitude', models.BigIntegerField(default=0)),
                ('laditude', models.BigIntegerField(default=0)),
                ('picture', models.ImageField(upload_to='media')),
                ('description', models.TextField(max_length=2500)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('duration', models.CharField(max_length=50)),
                ('holiday', models.CharField(choices=[('FR', 'Friday'), ('SU', 'Sunday'), ('MA', 'Manday'), ('TU', 'Tuseday'), ('WE', 'Wednesday'), ('TH', 'Thersday')], default='FR', max_length=2)),
                ('night_shift', models.BooleanField(default=False)),
                ('picture', models.ImageField(null=True, upload_to='static\\PublicServes\\images')),
                ('longitude', models.BigIntegerField(default=0)),
                ('laditude', models.BigIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanical',
            fields=[
                ('ip_m', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('ip_type', models.CharField(choices=[('ME', 'Mechanical'), ('EL', 'Elctronical'), ('KO', 'Komaje'), ('SO', 'Soaaje')], default='ME', max_length=2)),
                ('holiday', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static\\PublicServes\\images')),
                ('longitude', models.BigIntegerField(default=0)),
                ('laditude', models.BigIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('mechanical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('ip_h', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('ip_t', models.CharField(choices=[('GO', 'Goverment'), ('PR', 'Private')], default='GO', max_length=2)),
                ('competence', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static\\PublicServes\\images')),
                ('longitude', models.BigIntegerField(default=0)),
                ('laditude', models.BigIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('ip_s', models.CharField(choices=[('OP', 'EYE doctor'), ('CA', 'Hart doctor'), ('BO', 'Bons doctor'), ('AS', 'Beuaty doctor'), ('NE', 'Brain doctor '), ('PE', 'Children doctor')], default='OP', max_length=2)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('holiday', models.CharField(max_length=50)),
                ('longitude', models.BigIntegerField(default=0)),
                ('laditude', models.BigIntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static\\PublicServes\\images')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
