# Generated by Django 4.2.2 on 2023-07-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_transportscompany_pharmacies_mechanical_hospitals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='competence',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='specialization',
            field=models.CharField(choices=[('CART', 'Radiotheraoy or Chemptherapy'), ('CHILDREN', 'Children hospital'), ('HAAB', 'Hart and Body hospital'), ('SIAB', 'Mental and crazies hospital'), ('BRAN', 'Brain and Narrow hospital'), ('ALSP', 'All Specialest hospital')], default='ALSP', max_length=8),
        ),
    ]
