# Generated by Django 4.2.2 on 2023-07-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_remove_hospitals_competence_hospitals_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='laditude',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='longitude',
            field=models.BigIntegerField(),
        ),
    ]
