# Generated by Django 4.2.2 on 2023-07-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_alter_hospitals_laditude_alter_hospitals_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='laditude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='laditude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mechanical',
            name='laditude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mechanical',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='laditude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transportscompany',
            name='laditude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transportscompany',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
