# Generated by Django 4.2.2 on 2023-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_alter_doctors_laditude_alter_doctors_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='laditude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='laditude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
