# Generated by Django 4.2.2 on 2023-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_alter_hospitals_description_alter_hospitals_laditude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='laditude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
