# Generated by Django 4.2.2 on 2023-07-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0008_alter_doctors_laditude_alter_doctors_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='holiday',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='laditude',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='longitude',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='mechanical',
            name='holiday',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mechanical',
            name='laditude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mechanical',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transportscompany',
            name='description',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='transportscompany',
            name='laditude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transportscompany',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transportscompany',
            name='picture',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
