# Generated by Django 4.2.2 on 2023-07-08 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0009_alter_doctors_holiday_alter_doctors_laditude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
