# Generated by Django 4.2.2 on 2023-07-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0010_alter_doctors_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='hospital_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mechanical',
            name='mechanical_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='pharmacy_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportscompany',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
