# Generated by Django 4.2.2 on 2023-07-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0011_hospitals_hospital_name_mechanical_mechanical_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='user_type',
            field=models.CharField(choices=[('US', 'User'), ('PH', 'Pharmacy'), ('ME', 'Mechanical'), ('TR', 'Transport'), ('DR', 'Doctor'), ('HO', 'Hospital')], default='US', max_length=4),
        ),
    ]
