# Generated by Django 4.2.2 on 2023-06-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportsCompany',
            fields=[
                ('ip_tc', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name_tc', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13)),
                ('site', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='media')),
                ('description', models.TextField(max_length=2500)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('ip_type', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('ip_t', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('ip_tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transportscompany')),
                ('ip_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transporttype')),
            ],
        ),
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('rating', models.IntegerField()),
                ('ip_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.trips')),
            ],
        ),
    ]
