# Generated by Django 4.2.2 on 2023-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_transportscompany_name_tc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporttype',
            name='ip_type',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
