# Generated by Django 4.2.2 on 2023-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_transporttype_ip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='ip_t',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
