# Generated by Django 4.2.2 on 2023-07-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_trips_ip_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportscompany',
            name='rating',
        ),
    ]
