# Generated by Django 4.2.2 on 2023-07-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_remove_transportscompany_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportscompany',
            name='site',
        ),
        migrations.AddField(
            model_name='transportscompany',
            name='laditude',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportscompany',
            name='longitude',
            field=models.BigIntegerField(default=0),
        ),
    ]
