# Generated by Django 4.2.2 on 2023-07-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_remove_transportscompany_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='ip_type',
        ),
        migrations.AddField(
            model_name='trips',
            name='Type',
            field=models.CharField(choices=[('VI', 'Vip'), ('NO', 'Normal')], default='NO', max_length=2),
        ),
    ]
