# Generated by Django 4.2.2 on 2023-07-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_remove_trips_ip_type_trips_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportservice',
            name='date_time',
        ),
    ]
