# Generated by Django 4.2.2 on 2023-07-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_transportscompany_pharmacies_mechanical_hospitals_and_more'),
        ('transport', '0008_remove_transportservice_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='ip_tc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.transportscompany'),
        ),
        migrations.DeleteModel(
            name='TransportsCompany',
        ),
    ]
