# Generated by Django 4.2.2 on 2023-07-09 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0014_alter_hospitals_hospital_alter_mechanical_mechanical_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0009_alter_trips_ip_tc_delete_transportscompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.transportscompany')),
            ],
        ),
    ]
