# Generated by Django 4.2.2 on 2023-06-23 08:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanical',
            fields=[
                ('ip_m', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name_m', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('holiday', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static\\PublicServes\\images')),
                ('site', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVechale',
            fields=[
                ('ip_type', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('ip_type', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(null=10)),
                ('comments', models.CharField(max_length=2500)),
                ('ip_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicals.mechanical')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicals.mechanical')),
                ('ip_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicals.typevechale')),
            ],
        ),
    ]
