# Generated by Django 4.2.2 on 2023-06-23 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mechanicals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicalreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mechanicalreview',
            name='mechanical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicals.mechanical'),
        ),
        migrations.AddField(
            model_name='mechanical',
            name='ip_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicals.typework'),
        ),
    ]
