# Generated by Django 4.2.2 on 2023-07-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicals', '0003_remove_mechanical_name_m_remove_mechanical_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanical',
            name='site',
        ),
        migrations.RemoveField(
            model_name='mechanicservice',
            name='date_time',
        ),
        migrations.AddField(
            model_name='mechanical',
            name='laditude',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mechanical',
            name='longitude',
            field=models.BigIntegerField(default=0),
        ),
    ]
