# Generated by Django 4.2.2 on 2023-07-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicals', '0005_alter_mechanicalreview_mechanical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicalreview',
            name='rate',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')]),
        ),
    ]
