# Generated by Django 4.2.2 on 2023-07-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicals', '0006_alter_mechanicalreview_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicalreview',
            name='rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
