# Generated by Django 4.2.2 on 2023-07-07 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_s', models.CharField(choices=[('OP', 'EYE doctor'), ('CA', 'Hart doctor'), ('BO', 'Bons doctor'), ('AS', 'Beuaty doctor'), ('NE', 'Brain doctor '), ('PE', 'Children doctor')], default='OP', max_length=2)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('holiday', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=70)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static\\PublicServes\\images')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('ip_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctors')),
            ],
        ),
    ]
