# Generated by Django 4.2.2 on 2023-07-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
