# Generated by Django 4.2.2 on 2023-07-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctors_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='site',
        ),
        migrations.AddField(
            model_name='doctors',
            name='laditude',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='longitude',
            field=models.BigIntegerField(default=0),
        ),
    ]
