# Generated by Django 4.2.2 on 2023-07-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_transportscompany_pharmacies_mechanical_hospitals_and_more'),
        ('doctor', '0003_remove_doctors_rate_remove_doctors_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctarservice',
            name='ip_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.doctors'),
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
